# Generated by Django 4.2.14 on 2025-08-28 03:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('NB', 'Notebook'), ('TB', 'Tablet'), ('AL', 'Alargue')], max_length=2)),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('USO', 'En uso'), ('MANT', 'Mantenimiento')], default='DISP', max_length=5)),
                ('uso_acumulado_horas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usos_acumulados', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('SEC', 'Secundario'), ('SUP', 'Superior'), ('PER', 'Personal/Docente')], max_length=3)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=1)),
                ('aula', models.CharField(blank=True, max_length=20)),
                ('solicitante', models.CharField(blank=True, max_length=80)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin_prevista', models.DateTimeField()),
                ('fin_real', models.DateTimeField(blank=True, null=True)),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(default='activo', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=15)),
                ('severidad', models.IntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='core.item')),
            ],
        ),
    ]
