# Generated by Django 4.2.14 on 2025-08-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fin_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
