# Generated by Django 4.2.14 on 2025-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_prestamo_fin_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='anio',
            field=models.IntegerField(blank=True, choices=[(1, '1°'), (2, '2°')], null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='carrera',
            field=models.CharField(blank=True, choices=[('TCD', 'Tecnicatura en Ciencia de Datos'), ('PTEC', 'Profesorado en Tecnologías')], max_length=4, null=True),
        ),
    ]
