# Generated by Django 4.2.14 on 2025-08-28 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_prestamo_anio_prestamo_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('DISP', 'Disponible'), ('USO', 'En uso'), ('MANT', 'Mantenimiento'), ('RES', 'Reservado')], default='DISP', max_length=5),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NB', 'Notebook'), ('TB', 'Tablet'), ('AL', 'Alargue')], max_length=2)),
                ('nivel', models.CharField(choices=[('SEC', 'Secundario'), ('SUP', 'Superior'), ('PER', 'Personal/Docente')], max_length=3)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=1)),
                ('aula', models.CharField(blank=True, max_length=20)),
                ('solicitante', models.CharField(blank=True, max_length=80)),
                ('discord_user_id', models.CharField(blank=True, max_length=32)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField()),
                ('estado', models.CharField(default='activa', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('SEC', 'Secundario'), ('SUP', 'Superior'), ('PER', 'Personal/Docente')], default='SEC', max_length=3)),
                ('carrera', models.CharField(blank=True, choices=[('TCD', 'Tecnicatura en Ciencia de Datos'), ('PTEC', 'Profesorado en Tecnologías')], max_length=4, null=True)),
                ('anio', models.IntegerField(blank=True, choices=[(1, '1°'), (2, '2°')], null=True)),
                ('discord_user_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
