# Generated by Django 4.2.14 on 2025-08-29 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_item_estado_reserva_profile_discordlinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aprobada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancel_motivo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancelada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('convertida', 'Convertida'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='activa', max_length=12),
        ),
    ]
